# Generated by Django 6.0 on 2026-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_message_template', models.TextField(blank=True, help_text='Mensaje que se usará al abrir el DM desde el CTA del footer.', verbose_name='Mensaje DM Instagram (CTA footer)')),
            ],
            options={
                'verbose_name': 'Configuración developer',
                'verbose_name_plural': 'Configuración developer',
            },
        ),
    ]
