# Generated by Django 6.0 on 2026-01-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='Número de WhatsApp (sin + ni espacios)')),
                ('instagram_username', models.CharField(blank=True, max_length=100, verbose_name='Usuario de Instagram')),
                ('facebook_page', models.CharField(blank=True, max_length=100, verbose_name='Página de Facebook')),
                ('mercadolibre_store', models.CharField(blank=True, max_length=100, verbose_name='Tienda de MercadoLibre')),
                ('whatsapp_message_template', models.TextField(default="Hola! Estoy interesado/a en el producto '{{ product }}'", help_text='Usar {{ product }} para el nombre del producto.', verbose_name='Mensaje automático de WhatsApp')),
            ],
            options={
                'verbose_name': 'Configuración de la tienda',
                'verbose_name_plural': 'Configuración de la tienda',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': [],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mercadolibre', 'MercadoLibre'), ('external', 'Externo')], max_length=20, verbose_name='Tipo de link')),
                ('url', models.URLField(blank=True, verbose_name='URL (Solo external)')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Texto del botón (Solo external)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Link de producto',
                'verbose_name_plural': 'Links de producto',
                'ordering': ['order'],
            },
        ),
    ]
