# Generated by Django 6.0 on 2025-12-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': [], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
