# Generated by Django 6.0 on 2026-01-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='button_text',
            field=models.CharField(max_length=100, verbose_name=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'FaceBook'), ('mercadolibre', 'MercadoLibre'), ('external', 'Externo')], max_length=20, verbose_name='Tipo de link')),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='link_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'FaceBook'), ('mercadolibre', 'MercadoLibre'), ('external', 'Externo')], max_length=20, verbose_name='Tipo de link'),
        ),
    ]
