# Generated by Django 6.0 on 2026-01-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productlink_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto del botón'),
        ),
    ]
