# Generated by Django 6.0 on 2026-01-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productlink_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='Número de WhatsApp')),
                ('instagram_username', models.CharField(blank=True, max_length=100, verbose_name='Usuario de Instagram')),
                ('facebook_page', models.CharField(blank=True, max_length=100, verbose_name='Página de Facebook')),
                ('mercadolibre_store', models.CharField(blank=True, max_length=100, verbose_name='Tienda de MercadoLibre')),
            ],
        ),
    ]
