# Generated by Django 6.0 on 2026-01-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_storeconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeconfig',
            options={'verbose_name': 'Configuración de la tienda', 'verbose_name_plural': 'Configuración de la tienda'},
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de WhatsApp (sin + ni espacios)'),
        ),
    ]
