# Generated by Django 6.0 on 2026-01-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_storeconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='whatsapp_message_template',
            field=models.TextField(default="Hola! Estoy interesado/a en el producto '{{ product }}'", help_text='Usar {{ product }} para el nombre del producto.', verbose_name='Mensaje automático de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
