# Generated by Django 6.0 on 2026-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_storeconfig_whatsapp_message_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto del botón (Solo external)'),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='link_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mercadolibre', 'MercadoLibre'), ('external', 'Externo')], max_length=20, verbose_name='Tipo de link'),
        ),
        migrations.AlterField(
            model_name='productlink',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL (Solo external)'),
        ),
    ]
