# Generated by Django 6.0 on 2026-01-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productlink_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='link_type',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('mercadolibre', 'MercadoLibre'), ('external', 'Externo')], max_length=20, verbose_name='Tipo de link'),
        ),
    ]
