# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalog', '0009_alter_product_options_remove_product_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='store',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='config',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horario'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='URL de ubicación'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                fields=('store', 'slug'),
                name='catalog_category_store_slug_unique'
            ),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(
                fields=('store', 'slug'),
                name='catalog_product_store_slug_unique'
            ),
        ),
    ]
