# Generated by Django 6.0

from django.conf import settings
from django.db import migrations


def migrate_to_store(apps, schema_editor):
    Store = apps.get_model('core', 'Store')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')
    StoreConfig = apps.get_model('catalog', 'StoreConfig')

    # Obtener usuario owner o el primer usuario
    owner = User.objects.filter(is_owner=True).first()
    if not owner:
        owner = User.objects.first()
    if not owner:
        return  # Sin usuarios, no hay datos que migrar

    # Crear Store por defecto con datos de settings
    from django.conf import settings as django_settings
    default_slug = "catalogico"
    store, _ = Store.objects.get_or_create(
        slug=default_slug,
        defaults={
            'name': getattr(django_settings, 'SITE_NAME', 'Catalógico'),
            'owner': owner,
            'is_active': True,
        }
    )

    def _insta_user(val):
        if not val:
            return ''
        val = (val or '').strip().rstrip('/')
        if 'instagram.com/' in val:
            return val.split('instagram.com/')[-1] or ''
        return val

    addr = getattr(django_settings, 'STORE_ADDRESS', '') or ''
    hours = getattr(django_settings, 'STORE_HOURS', '') or ''
    loc_url = getattr(django_settings, 'STORE_LOCATION_URL', '') or ''
    wa = getattr(django_settings, 'STORE_WHATSAPP', '') or ''
    ig = _insta_user(getattr(django_settings, 'STORE_INSTAGRAM', ''))

    config = StoreConfig.objects.first()
    if config:
        config.store = store
        config.address = addr
        config.hours = hours
        config.location_url = loc_url
        if not config.whatsapp_number:
            config.whatsapp_number = wa
        if not config.instagram_username:
            config.instagram_username = ig
        config.save()
    else:
        StoreConfig.objects.create(
            store=store,
            address=addr,
            hours=hours,
            location_url=loc_url,
            whatsapp_number=wa,
            instagram_username=ig,
        )

    # Asignar categorías y productos al store
    Category.objects.filter(store__isnull=True).update(store=store)
    Product.objects.filter(store__isnull=True).update(store=store)


def reverse_migrate(apps, schema_editor):
    StoreConfig = apps.get_model('catalog', 'StoreConfig')
    Category = apps.get_model('catalog', 'Category')
    Product = apps.get_model('catalog', 'Product')

    StoreConfig.objects.all().update(store=None)
    Category.objects.all().update(store=None)
    Product.objects.all().update(store=None)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_add_store_fk'),
    ]

    operations = [
        migrations.RunPython(migrate_to_store, reverse_migrate),
    ]
