# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_migrate_data_to_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='store',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='config',
                to='core.store',
                verbose_name='Tienda'
            ),
        ),
    ]
