# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_store_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la tienda (header y favicon)', null=True, upload_to='stores/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_bg',
            field=models.CharField(blank=True, default='#ffffff', help_text='Fondo general de la tienda', max_length=7, verbose_name='Color fondo de página'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_surface',
            field=models.CharField(blank=True, default='#f8f8f8', help_text='Tarjetas, cajas, áreas elevadas', max_length=7, verbose_name='Color superficies'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_text',
            field=models.CharField(blank=True, default='#111111', help_text='Texto principal de la tienda', max_length=7, verbose_name='Color texto principal'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_primary',
            field=models.CharField(blank=True, default='#3483fa', help_text='Botones, enlaces, detalles destacados', max_length=7, verbose_name='Color primario'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_primary_hover',
            field=models.CharField(blank=True, default='#468cf6', help_text='Hover sobre botones y enlaces', max_length=7, verbose_name='Color primario al pasar el mouse'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_border',
            field=models.CharField(blank=True, default='#e0e0e0', help_text='Líneas separadoras y bordes', max_length=7, verbose_name='Color bordes'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_muted',
            field=models.CharField(blank=True, default='#6b6b6b', help_text='Texto de menor importancia', max_length=7, verbose_name='Color texto secundario'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_bg_dark',
            field=models.CharField(blank=True, default='#121212', help_text='Fondo general de la tienda', max_length=7, verbose_name='Color fondo de página (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_surface_dark',
            field=models.CharField(blank=True, default='#1e1e1e', help_text='Tarjetas, cajas, áreas elevadas', max_length=7, verbose_name='Color superficies (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_text_dark',
            field=models.CharField(blank=True, default='#f5f5f5', help_text='Texto principal de la tienda', max_length=7, verbose_name='Color texto principal (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_primary_dark',
            field=models.CharField(blank=True, default='#3483fa', help_text='Botones, enlaces, detalles destacados', max_length=7, verbose_name='Color primario (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_primary_hover_dark',
            field=models.CharField(blank=True, default='#468cf6', help_text='Hover sobre botones y enlaces', max_length=7, verbose_name='Color primario al pasar el mouse (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_border_dark',
            field=models.CharField(blank=True, default='#333333', help_text='Líneas separadoras y bordes', max_length=7, verbose_name='Color bordes (modo oscuro)'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_muted_dark',
            field=models.CharField(blank=True, default='#aaaaaa', help_text='Texto de menor importancia', max_length=7, verbose_name='Color texto secundario (modo oscuro)'),
        ),
    ]
