# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_add_store_config_colors_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='color_surface_secondary',
            field=models.CharField(blank=True, default='#f0f0f0', help_text='Tarjetas alternativas, headers', max_length=7, verbose_name='Color superficies secundarias'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='color_surface_secondary_dark',
            field=models.CharField(blank=True, default='#2a2a2a', help_text='Tarjetas alternativas, headers', max_length=7, verbose_name='Color superficies secundarias (modo oscuro)'),
        ),
    ]
