# Generated by Django 6.0

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_add_surface_secondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
