# Generated by Django 6.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalog', '0015_remove_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('hours', models.CharField(blank=True, max_length=200, verbose_name='Horarios')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ciudad'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='has_physical_store',
            field=models.BooleanField(default=False, verbose_name='¿Tiene local físico?'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='has_multiple_branches',
            field=models.BooleanField(default=False, verbose_name='¿Tiene más de un local físico?'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_link_whatsapp',
            field=models.BooleanField(default=False, verbose_name='WhatsApp por defecto'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_link_instagram',
            field=models.BooleanField(default=False, verbose_name='Instagram por defecto'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_link_facebook',
            field=models.BooleanField(default=False, verbose_name='Facebook por defecto'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_link_mercadolibre',
            field=models.BooleanField(default=False, verbose_name='MercadoLibre por defecto'),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Horarios'),
        ),
    ]
