# Generated by Django 6.0 on 2026-02-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_storeconfig_branch_default_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='storeconfig',
            name='whatsapp_message_template',
            field=models.TextField(default="Hola! Estoy interesado/a en el producto '{{ product }}'", help_text='Usar {{ product }} para el nombre del producto.', verbose_name='Mensaje automático (WhatsApp e Instagram)'),
        ),
    ]
