# Generated by Django 6.0 on 2026-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_slug_constraint'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='product',
            name='catalog_product_store_slug_unique',
            constraint=models.UniqueConstraint(
                fields=['store', 'slug'],
                condition=models.Q(('status', 'published')),
                name='catalog_product_store_slug_unique',
            ),
        ),
    ]
