# Generated by Django 6.0 on 2026-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_conditional_slug_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['id'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='has_multiple_branches',
        ),
        migrations.RemoveField(
            model_name='storeconfig',
            name='has_physical_store',
        ),
        migrations.AddField(
            model_name='branch',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='URL de Google Maps'),
        ),
    ]
