# Generated by Django 6.0 on 2026-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_info_contact_branches_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='whatsapp_message_template',
            field=models.TextField(default="Hola! Estoy interesado/a en el producto '{{ product }}' ({{ url }})", help_text='Usar {{ product }} para el nombre del producto y {{ url }} para la URL del producto.', verbose_name='Mensaje automático (WhatsApp e Instagram)'),
        ),
    ]
