# Generated by Django 6.0 on 2026-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_message_template_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de WhatsApp'),
        ),
    ]
