# Generated by Django 6.0 on 2026-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_storeconfig_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='URL de Google Maps (Generado automáticamente al guardar)'),
        ),
    ]
