# Generated by Django 6.0 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_branch_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='URL de Google Maps (generado automáticamente al guardar)'),
        ),
    ]
