# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_branch_location_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='order_message_template',
            field=models.TextField(
                blank=True,
                help_text='Usar {{ items }} para la lista de productos y {{ total }} para el total. Mismo mensaje para ambos canales.',
                verbose_name='Mensaje del pedido del carrito (WhatsApp e Instagram)',
            ),
        ),
    ]
