# Generated by Django

from django.db import migrations, models


def set_default_order_message(apps, schema_editor):
    """Rellena el mensaje por defecto en tiendas que lo tienen vacío."""
    StoreConfig = apps.get_model("catalog", "StoreConfig")
    default = "Hola, mi pedido:\n{{ items }}\nTotal: {{ total }}"
    StoreConfig.objects.filter(order_message_template="").update(order_message_template=default)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_storeconfig_order_message_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconfig',
            name='order_message_template',
            field=models.TextField(
                blank=True,
                default="Hola, mi pedido:\n{{ items }}\nTotal: {{ total }}",
                help_text='Usar {{ items }} para la lista de productos (nombre y cantidad por línea) y {{ total }} para el total. Mismo mensaje para WhatsApp e Instagram.',
                verbose_name='Mensaje del pedido del carrito (WhatsApp e Instagram)',
            ),
        ),
        migrations.RunPython(set_default_order_message, migrations.RunPython.noop),
    ]
