# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_storeconfig_order_message_template_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text='Dejar vacío si no controlás el stock. En 0 no se puede agregar al carrito.',
                null=True,
                verbose_name='Stock',
            ),
        ),
    ]
