# Generated by Django 6.0 on 2026-02-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Dejar vacío si no controlás el stock.', null=True, verbose_name='Stock'),
        ),
    ]
